# Generated by Django 6.0.7 on 2026-07-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_loan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do empréstimo')),
                ('interest_mounth', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Juros mensal')),
            ],
        ),
    ]
